### ISSUE TITLE
Insufficient taxonomic resolution: modify ltg_params?

### ISSUE THREAD

**Issue by Anto007** [meglecz/mkLTG#2]
Hi Emese,

mkLTG looks like a promising tool for barcoding analysis. I ran some tests with a small test dataset of mine and I found the taxonomic resolution to be a bit insufficient. I used the latest COInr database that you made available[ here](https://osf.io/y9pha)) and here are my 4 ASV sequences if you would like to test them yourself 
[test_ASVs.fa.txt](https://github.com/user-attachments/files/17323639/test_ASVs.fa.txt)

Below is a screenshot of the results that I got after running mkLTG.
![image](https://github.com/user-attachments/assets/6b91ccd1-38c8-4662-b2c7-50632b6baeb7)

and below is a screenshot of the results that I got after running BOLDigger2 package that directly queries the BOLD database.
![image](https://github.com/user-attachments/assets/3fbccd19-b024-4cc1-a9ba-71362aafb729)

My question is why mkLTG wasn't able to resolve at least until the genus level for ASVs 2-4 and the order level for ASV_1? I realize that the identity cutoff/threshold values aren't comparable between mkLTG but I was hoping to know from you how I should modify the *params.tsv file for mkLTG to get the kind of taxonomic resolution that I got in BOLDigger2? Sorry, I'm a bit unclear as to how the content of the params file needs to be set as this part is not explained in detail in your README. With the default params file, I got even worse taxonomic resolution for these 4 ASVs and so I modified the params file for my run to look like the below. I would appreciate it very much in case you have got any suggestions for better tweaks here.

pid	pcov	phit	taxn	seqn	refres	ltgres
100	70	70	1	1	species	species
98	70	70	1	1	species	species
95	70	70	2	2	genus	species
87	70	70	3	3	family	genus
83	70	70	4	4	order	family
80	70	70	4	4	class	order
79	70	70	5	5	phylum	order
70	70	70	5	5	kingdom	phylum

**Comment by meglecz** [comment]
Hello,

BOLDigger2 is great as it can access private sequences from BOLD, which are preciously hidden in BOLD and not possible to download them via API. As a consequence, the private sequences of BOLD are not in COInr. So this is one part of the differences.

For finding the right parameters and explication on their sense, you might have read my paper in Biologia Futura (read only access: https://rdcu.be/dxABF). Here is the explantation for each of the ASVs. I attach screenshots of BOLD system identification, since it is visible which are the private and public sequences. 

ASV1 
The 89.35 % identity in the BOLDigger output is the best hit, and it is a private sequence. 
It is a sequence from Gobiformes or not ? Difficult to say. The best hits have around 90% identify, and there is a Perciformes among them, so I have some doubts.
mkLTG gives a more conservative result. Among public sequences, there are no hits above 87% identity, and if we go down to 83, the last common ancestor is Actinopterygii.

![ASV1](https://github.com/user-attachments/assets/56dd4d79-b1a6-4402-ae4a-c7500f1e0d1b)


ASV2
The best hits have >99% identity, but these sequences are eliminated by the refres=species parameter in mkLTG. In COInr non-standard taxon names  (sp. KSA_1682,  sp. Red Sea 3 CA-2019) are ignored and the sequence is registered to the taxon name of higher level (Eviota genus in this case).
Here it is very likely that the sequence is Eviota, and mkLTG could give this result by setting refres=genus at 98% level. 

![ASV2](https://github.com/user-attachments/assets/6118eac2-923f-43f9-9db7-737fbc2a1852)

ASV3
We have some very good hits among the private and public sequences (>99%). The public ones are encoded till the genus level in COInr. (E. sp. KSA_1582 and E. cf. prasina CA-2019 are not accepted as valid species names), so there is no taxonomic assignment at 100% and 98% level (refres=species)
At 95% there is no assignment, since all hits are registered as Eviota, so there is only one taxon, but 2 is necessary according to your settings (taxn=2).
At 87%, there are 2 taxa, but (taxn is set to 3). 
At 83% the LTG is Gobiidae, since there are different genera among the hits at this level.
How to fix this :
Set refseq=species at 100% and refseq=genus at 98%. This would give Eviota based on the public sequences and Eviota pardalota, if private sequence were included in COInr.
Le result given by BOLDigger is Eviota pardalota. This might be the case, we should not forget that there are also very good hits to other sequences that are not annotated as Eviota pardalota. So this might be an over-interpretation.

![ASV3](https://github.com/user-attachments/assets/69edc780-847d-44e2-abd4-10df139d2f61)

ASV4
Seems quite clear. The two assignments are the same.

As shown in the paper describing mkLTG, the default parameter setting is defined based on a high number of assignments. However, I think there is no method the gets everything correctly.
For the ASV, you sent me, it seems to be a good idea to set refres to genus at 98%. You can leave it to species at 100%. 
Unfortunately, I cannot fix the problem of not being able to access the private sequences in BOLD.

I hope it helps,
Emese

**Comment by Anto007** [comment]
Thanks a zillion @meglecz for your detailed explanation- much appreciated. Modifying the params file in line with your suggestions gave me results that were close to what I expected. I'll now go ahead and run more extensive tests with some of the larger COI ASV datasets that I've got with me. One last question out of curiosity- do you plan to make available an updated version of the coi database every 6 months or at least once every year? Closing this issue and thank you again for your valuable time.

**Comment by meglecz** [comment]
I am glad my answers helped. 

Yes, COInr is updated each year in May, but if you need un update in between, a detailed tutorial is found here: https://mkcoinr.readthedocs.io/en/latest/content/tutorial.html#create-coinr-from-bold-and-ncbi

The scripts are available here : https://github.com/meglecz/mkCOInr

Emese
